name: crypto_wallet
description: Sua carteira rapida de cotações.
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=2.17.0 <=4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_dotenv: ^5.0.2
  universal_html: ^2.0.8
  dio: ^4.0.6
  shared_preferences: ^2.2.2
  carousel_slider: ^4.1.1
  syncfusion_flutter_charts: ^20.3.52
  webview_flutter: ^3.0.4
  import_sorter: ^4.6.0
  go_router: ^7.0.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  mocktail: ^1.0.1
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "icone_app"
  ios: true
  image_path: "lib/assets/images/logo-apk.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/logo-apk.png
    - lib/assets/images/bitcoin-logo.png
    - lib/assets/images/ethereum-logo.png
    - lib/assets/images/litecoin-logo.png
    - lib/assets/images/monero-logo.png
    - lib/assets/images/solano-logo.png
    - lib/assets/images/tether-logo.png
    - lib/assets/images/homecard-1.png
    - lib/assets/images/homecard-2.png
    - lib/assets/images/homecard-3.png
    - lib/assets/images/homecard-4.png
    - lib/assets/images/profile-effigy.png
